# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
labimg: images/alcyon.jpg
title: ALCYON lab
email: zafeirakopoulos@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ALCYON lab
  Algorithms, Algebra, Combinatorics, Geometry, Optimization and Number Theory
baseurl: "/lab" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
#https://alcyon-lab.gitlab.io
twitter: alcyonlab
# github_username:  jekyll
linkedin: groups/8811634/
# Build settings
markdown: kramdown
remote_theme: minima
# plugins:
  # - jekyll-feed
#
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

excerpt_separator: "<!--more-->"

collections_dir: collections
collections:
  members:
    people: true
    output: true
  proceedings:
    output: false
    sort_by: year
  books:
    output: false
  preprints:
    output: false
    sort_by: year
  articles:
    output: false
  journal:
    output: false
    sort_by: year
  theses:
    output: false
  events:
    output: true
  talks:
    output: false
  seminar:
    output: true
  projects:
    output: true
  news:
    output: false
  software:
    output: true
  topics:
    output: true
  scim:
    output: true
